// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhgfiveqtvpgtvzjykzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZoZ2ZpdmVxdHZwZ3R2emp5a3p5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYxMzg1ODQsImV4cCI6MjA3MTcxNDU4NH0.SIGEWnsrLfU02QNi6Qzz1M9anhzSi72kTEjxSU85Gmw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});